config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "brains#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
  resources :brains do
    resources :bookings, except: :index do
      member do
        patch :accept
        patch :reject
      end
    end
    resources :reviews, except: %i[show index]
  end

  resources :users, except: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :brain

  validates :start_date, presence: true
  validates :end_date, presence: true

  enum status: { pending: "pending", accepted: "approved", rejected: "rejected" }

  # validate :end_date_after_start_date
  # validate :start_date_not_in_past

  # private

  # def end_date_after_start_date
  #   return if end_date.blank? || start_date.blank?

  #   errors.add(:end_date, "must be after the start date") if end_date < start_date
  # end

  # def start_date_not_in_past
  #   errors.add(:start_date, "can't be in the past") if start_date < Date.today
  #   errors.add(:end_date, "can't be in the past") if end_date < Date.today
  # end
end

app/models/brain.rb
class Brain < ApplicationRecord
  LANGUAGES = ["French", "English", "Italian", "Mandarin", "Spanish"]
  SPECIALTIES = ["Humor", "Eloquence", "Dev Profil", "Artist Soul", "Sporty Mindset"]

  belongs_to :user
  has_many :bookings, dependent: :destroy
  has_many :reviews
  has_one_attached :photo

  validates :name, presence: true, uniqueness: true
  validates :qi, inclusion: { in: 0..180 }, numericality: { only_integer: true }
  validates :price_per_day, presence: true
  validates :languages, inclusion: { in: LANGUAGES }
  validates :specialties, inclusion: { in: SPECIALTIES }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :brain

  validates :comment, presence: true, length: { minimum: 5 }
  validates :rating, inclusion: { in: 1..5 }, numericality: { only_integer: true }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :bookings
  has_many :brains, dependent: :destroy

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :pseudo, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    user_path(current_user.id)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :set_brain, only: [:show, :new, :create, :destroy, :accept, :reject]
  before_action :set_user, only: [:show, :new, :create, :accept, :reject]

  def show
    @booking = Booking.find(params[:id])

  end

  def new
    @bookings = Booking.where(brain_id: @brain.id)
    @price = @brain.price_per_day
    @dates_booking = @bookings.map { |booking| { from: booking.start_date, to: booking.end_date } }.to_json
    @booking = Booking.new
  end

  def create
    if current_user
      @booking = Booking.new(booking_params)
      @booking.user_id = @user.id
      @booking.brain_id = @brain.id
      if @booking.save!
        total_price =  @brain.price_per_day * (@booking.end_date - @booking.start_date).to_i
        @booking.update!(total_price: total_price)
        redirect_to brain_booking_path(@brain.id, @booking)
      else
        render :new, status: :unprocessable_entity
      end
    else
      redirect_to new_user_session_path
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.brain_id = @brain.id
    @booking.destroy
    redirect_to user_path(current_user.id), status: :see_other
  end

  def accept
    @booking = Booking.find(params[:id])
    @booking.update(status: 'approved')
    redirect_to user_path(@user), notice: "Booking successfully accepted!"
  end

  def reject
    @booking = Booking.find(params[:id])
    @booking.update(status: 'rejected')
    redirect_to user_path(@user), notice: "Booking rejected!"
  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end

  def set_brain
    @brain = Brain.find(params[:brain_id])
  end

  def set_user
    @user = current_user
  end

end

app/controllers/brains_controller.rb
class BrainsController < ApplicationController
  before_action :set_brain, only: [:show, :edit, :update, :destroy]

  def index
    @brains = Brain.all
    # filter_brains if params[:filter].present?
  end

  def show
    @reviews = Review.where(brain_id: @brain.id)
    @user = current_user
    @booking = Booking.new
    @price = @brain.price_per_day
    @bookings = Booking.where(brain_id: @brain.id)
    @dates_booking = @bookings.map { |booking| { from: booking.start_date, to: booking.end_date } }.to_json
  end

  def new
    @brain = Brain.new
  end

  def create
    @brain = Brain.new(brain_params)
    @brain.user_id = current_user.id
    if @brain.save
      redirect_to brain_path(@brain)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
  end

  def update
    @brain.update(brain_params)
    redirect_to brain_path(@brain)
  end

  def destroy
    @user = current_user
    @brain.destroy
    redirect_to user_path(@user.id), status: :see_other
  end

  private

  # def filter_brains
  #   if params[:filter][:qi].present?
  #     @brains = @brains.where("qi >= ?", params[:filter][:qi])
  #   end

  #   if params[:filter][:languages].present?
  #     selected_languages = params[:filter][:languages].reject(&:blank?)
  #     @brains = @brains.select { |brain| (brain.languages & selected_languages).present? }
  #   end

  #   if params[:filter][:specialties].present?
  #     selected_specialties = params[:filter][:specialties].reject(&:blank?)
  #     @brains = @brains.select { |brain| (brain.specialties & selected_specialties).present? }
  #   end

  #   if params[:filter][:price_per_day].present?
  #     @brains = @brains.where("price_per_day <= ?", params[:filter][:price_per_day])
  #   end
  # end

  def brain_params
    params.require(:brain).permit(:photo, :name, :qi, :price_per_day, languages: [], specialties: [])
  end

  def set_brain
    @brain = Brain.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_brain, only: [:new, :create]

  def new
    if current_user
      @review = Review.new(brain_id: @brain.id)
    else
      redirect_to new_user_session_path
    end
  end

  def create
    if current_user
      @review = Review.new(review_params)
      @review.brain_id = @brain.id
      if @review.save
        redirect_to brain_path(@brain)
      else
        render :new, status: :unprocessable_entity
      end
    else
      redirect_to new_user_session_path
    end
  end

  private

  def review_params
    params.require(:review).permit(:comment, :rating)
  end

  def set_brain
    @brain = Brain.find(params[:brain_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user

  def show
    @brains = Brain.where(user_id: current_user.id)
    @bookings = Booking.where(user_id: current_user.id)
    @received_bookings = []
    Brain.where(user: current_user).each { |brain| @received_bookings << brain.bookings }
    @received_bookings.flatten!
  end

  private

  def set_user
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/new.html.erb
<div class="container">
  <div class="row">
    <div class="col">

      <h1>Book this brain</h1>

      <div data-controller="price-calculator" data-price-calculator-priceperday-value=<%= @price %>>
        <%= simple_form_for [@brain, @booking]  do |f| %>
        <%= f.input :start_date,
                    as: :string,
                    input_html: { data: { controller: "datepicker", datepicker_date_value: @dates_booking, price_calculator_target: "start", action: "change->price-calculator#update"}} %>
        <%= f.input :end_date,
                    as: :string,
                    input_html: { data: { controller: "datepicker", datepicker_date_value: @dates_booking, price_calculator_target: "end", action: "change->price-calculator#update"}} %>
        <%= f.submit %>
        <% end %>
        <div>
          <p data-price-calculator-target="total" ></p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/bookings/show.html.erb
<div class="container">
  <div class="confirmation">
    <div class="thankyou">
      <h1>Thank you <%= @user.pseudo %></h1>
      <p>your reservation of <strong><%= @brain.name %></strong> will be final after validation by the owner...</p>
    </div>

    <div class="booking-date-confirmation">
      <div class="booking-date-infos">
        <p><strong>Start date : </strong><%= @booking.start_date %></p>
        <p><strong>End date : </strong><%= @booking.end_date %></p>
        <p><strong>Price : </strong><%= @booking.total_price %> €</p>
      </div>
    </div>
  </div>
  <div class="btn-back">
    <%= link_to "Back to your dashboard", user_path(@user), class: "main-button" %>
  </div>
</div>

app/views/brains/edit.html.erb
<div class="container">
  <%= simple_form_for(@brain, html: { class: 'brain-form' }) do |f| %>
    <div class="form-group">
      <%= f.input :name, label_html: { class: 'form-label' }, input_html: { class: 'form-control' }  %>
    </div>
    <div class="form-group">
      <%= f.input :qi, label_html: { class: 'form-label' }, input_html: { class: 'form-control' } %>
    </div>
    <div class="form-group">
      <%= f.input :languages, collection: Brain::LANGUAGES, multiple: true, as: :check_boxes, include_hidden: false, label_html: { class: 'form-label' }, item_wrapper_class: 'checkbox-wrapper', input_html: { class: 'form-check-input custom-checkbox' }  %>
    </div>
    <div class="form-group">
      <%= f.input :specialties, collection: Brain::SPECIALTIES, multiple: true, as: :check_boxes, include_hidden: false, label_html: { class: 'form-label' }, item_wrapper_class: 'checkbox-wrapper', input_html: { class: 'form-check-input custom-checkbox' }  %>
    </div>
    <div class="form-group">
      <%= f.input :price_per_day, label_html: { class: 'form-label' }, input_html: { class: 'form-control' }  %>
    </div>
    <div class="form-group">
      <%= f.input :photo, as: :file, label_html: { class: 'form-label' }, input_html: { class: 'form-control-file' }  %>
    </div>
    <%= f.submit 'Edit your brain', class: 'btn filter__btn' %>
  <% end %>
</div>

app/views/brains/index.html.erb
<div class="container">

  <div class="banner-brainz mb-5" style="background-image: url(<%= image_path("backgroundbanner.jpg")%>);">
    <div class="container">
      <h1>Mind your business...</h1>
      <h2>Rent a brain!</h2>
    </div>
  </div>

  <div class='d-flex justify-content-center mb-5'>
    <div class="filters-bar">
      <div class="filters-bar__category">
        <a href="">
          <i class="filters-bar__icon fa-solid fa-code"></i>
          <div class="filters-bar__text">Dev Profile</div>
        </a>
      </div>
      <div class="filters-bar__category">
        <a href="">
          <i class="filters-bar__icon fa-regular fa-face-smile"></i>
          <div class="filters-bar__text">Humor</div>
        </a>
      </div>
      <div class="filters-bar__category">
        <a href="">
          <i class="filters-bar__icon fa-solid fa-hands-clapping"></i>
          <div class="filters-bar__text">Eloquence</div>
        </a>
      </div>
      <div class="filters-bar__category">
        <a href="">
          <i class="filters-bar__icon fa-solid fa-football"></i>
          <div class="filters-bar__text">Sporty Mindset</div>
        </a>
      </div>
      <div class="filters-bar__category">
        <a href="">
          <i class="filters-bar__icon fa-solid fa-palette"></i>
          <div class="filters-bar__text">Artist Soul</div>
        </a>
      </div>
    </div>
  </div>

  <div class="main-container d-flex positiobn-relative mb-5" data-controller="filters">
    <div class="filters__sidebar bg-light p-5">
      <%= simple_form_for :filter, url: brains_path, data: { action:"submit->filters#update"} do |f| %>
        <div class="mb-3">
          <%= f.input :qi, label: "QI min", input_html: { data: { filters_target:"qi"}, class: "form-control" } %>
        </div>
        <div class="mb-3">
          <%= f.input :languages, collection: Brain::LANGUAGES, multiple: true, as: :check_boxes, include_hidden: false, class: "form-check-input", input_html: { data: { filters_target:"languages"}} %>
        </div>
        <div class="mb-3">
          <%= f.input :specialties, collection: Brain::SPECIALTIES, multiple: true, as: :check_boxes, include_hidden: false, input_html: { class: "form-check-input" }, input_html: {data: { filters_target:"specialties"}} %>
        </div>
        <div class="mb-3">
          <%= f.input :price_per_day, label: "Price Max", input_html: { data: { filters_target:"price"}, class: "form-control"} %>
        </div>
        <div class="text-end">
          <%= f.submit 'Filter', class: "btn filter__btn" %>
        </div>
      <% end %>
    </div>

    <div class="content">
  <div class="grid__cards mb-5">
    <% @brains.each do |brain| %>
      <%= link_to brain_path(brain), data: { filters_target:"card", price: brain.price_per_day, qi: brain.qi, languages: brain.languages.join(" "), specialties: brain.specialties } do %>
        <div class="card-index" >
          <div class="container-image mb-3">
            <% if brain.photo.attached? %>
              <%= cl_image_tag(brain.photo.key) %>
            <% else %>
              <%= image_tag("brainzImage.png", alt: "Brain Image") %>
            <% end %>
            <div class="qi">
              <div class="card-index__title">QI:</div>
              <div class="card-index__text-QI"><%= brain.qi %></div>
            </div>
          </div>
          <div class="card-infos">
            <div class="card-infos__attributes">
              <h2 class="card-index__name mb-3"><%= brain.name %></h2>

              <div class="d-flex align-items-start">
                <h3 class="card-index__title">Language(s):</h3>
                <div>
                  <% brain.languages.each do |language| %>
                    <p class="card-index__text"><%= language %></p>
                  <% end %>
                </div>
              </div>
              <div class="d-flex align-items-start">
                <h3 class="card-index__title">Specialties:</h3>
                <div>
                  <% brain.specialties.each do |specialty| %>
                    <p class="card-index__text"><%= specialty %></p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div>
            <div class="card-index__text-price"><%= brain.price_per_day %> € / Day</div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
</div>


    </div>
  </div>

app/views/brains/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="show-brain">

        <div class="brain-infos">
          <div class="card-show">
            <div class="delete-on-image">
              <div class="card-brain-img-show">
                <% if @brain.photo.attached? %>
                  <%= cl_image_tag(@brain.photo.key, width: 280) %>
                <% else %>
                  <%= image_tag "brainz-card-cyril.png", width: 280 %>
                <% end %>
              </div>
              <div class="delete">
                <% if current_user %>
                  <% if @user.id == @brain.user_id %>
                    <%= link_to brain_path(@brain), class: "btn btn-delete", data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} do%>
                      <i class="fa-solid fa-xmark" style="color: #322A3D;"></i>
                    <% end %>
                  <% end %>
                <% end %>
              </div>
            </div>

            <div class="card-brain-infos">
              <div class="card-name-qi">
                <h1><%= @brain.name %></h1>
                <div class="qi">
                  <h2>QI : </h2>
                  <h2 class="qi-value"><%= @brain.qi %></h2>
                </div>
              </div>

              <div class="card-languages-specialties">
                <h2>Language(s)</h2>
                <ul>
                  <% @brain.languages.each do |language| %>
                    <li><%= language %></li>
                  <% end %>
                </ul>

                <h2>Specialties</h2>
                <ul>
                  <% @brain.specialties.each do |speciality| %>
                    <li><%= speciality %></li>
                  <% end %>
                </ul>
              </div>

              <div class="price">
                <h3><%= @brain.price_per_day %> $</h3>
              </div>

              <div class="edit">
                <% if current_user %>
                  <% if @user.id == @brain.user_id %>
                    <%= link_to "Edit your brain", edit_brain_path(@brain), class: "btn filter__btn"%>
                  <% end %>
                <% end %>
              </div>
            </div>
          </div>

            <div class="card-reviews">
            <h1>Reviews</h1>
            <% @reviews.each do |review| %>
              <div class="review">
                <% case review.rating %>
                  <% when 1 %>
                    <p><i class="fa-solid fa-star" style="color: #FFD43B;"></i><i class="fa-regular fa-star" style="color: #FFD43B;"></i><i class="fa-regular fa-star" style="color: #FFD43B;"></i><i class="fa-regular fa-star" style="color: #FFD43B;"></i><i class="fa-regular fa-star" style="color: #FFD43B;"></i></p>
                  <% when 2 %>
                    <p><i class="fa-solid fa-star" style="color: #FFD43B;"></i><i class="fa-solid fa-star" style="color: #FFD43B;"></i><i class="fa-regular fa-star" style="color: #FFD43B;"></i><i class="fa-regular fa-star" style="color: #FFD43B;"></i><i class="fa-regular fa-star" style="color: #FFD43B;"></i></p>
                  <% when 3 %>
                    <p><i class="fa-solid fa-star" style="color: #FFD43B;"></i><i class="fa-solid fa-star" style="color: #FFD43B;"></i><i class="fa-solid fa-star" style="color: #FFD43B;"></i><i class="fa-regular fa-star" style="color: #FFD43B;"></i><i class="fa-regular fa-star" style="color: #FFD43B;"></i></p>
                  <% when 4 %>
                    <p><i class="fa-solid fa-star" style="color: #FFD43B;"></i><i class="fa-solid fa-star" style="color: #FFD43B;"></i><i class="fa-solid fa-star" style="color: #FFD43B;"></i><i class="fa-solid fa-star" style="color: #FFD43B;"></i><i class="fa-regular fa-star" style="color: #FFD43B;"></i></p>
                  <% when 5 %>
                    <p><i class="fa-solid fa-star" style="color: #FFD43B;"></i><i class="fa-solid fa-star" style="color: #FFD43B;"></i><i class="fa-solid fa-star" style="color: #FFD43B;"></i><i class="fa-solid fa-star" style="color: #FFD43B;"></i><i class="fa-solid fa-star" style="color: #FFD43B;"></i></p>
                <% end %>
                <p><i class="fa-solid fa-quote-left" style="color: #6931AB;"></i> <%= review.comment %></p>
              </div>
            <% end %>
          </div>
          <%= link_to "Add a review", new_brain_review_path(@brain), class: "btn main-button add-review"%>
        </div>



        <div class="card-bookings">
          <h1>Book your brain !</h1>
          <div class="booking-form">

            <div data-controller="price-calculator" data-price-calculator-priceperday-value=<%= @price %>>
              <%= simple_form_for [@brain, @booking]  do |f| %>
                <%= f.input :start_date,
                            as: :string,
                            input_html: { data: { controller: "datepicker", datepicker_date_value: @dates_booking, price_calculator_target: "start", action: "change->price-calculator#update"}} %>
                <%= f.input :end_date,
                            as: :string,
                            input_html: { data: { controller: "datepicker", datepicker_date_value: @dates_booking, price_calculator_target: "end", action: "change->price-calculator#update"}} %>
                <div class="book-button">
                  <%= f.submit "Book Me", class: "btn filter__btn"%>
                </div>
              <% end %>
            <div class="total-price">
              <p data-price-calculator-target="total"></p><p>€</p>
            </div>
            </div>

          </div>

        </div>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brainz</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Permanent+Marker&display=swap" rel="stylesheet">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&family=Permanent+Marker&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css">

    <%= javascript_importmap_tags %>
  </head>

  <body>
  <div class="container">
    <div class="navbar navbar-expand-sm navbar-light navbar-brainz mb-5 mt-3">
      <div class="container-fluid">
        <%= link_to brains_path, class: "navbar-brand" do%>
          <%= image_tag "brainz-logo-final.png" %>
        <% end %>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto">
              <% if current_user %>
                <li class="nav-item dropdown">
                  <img class="avatar dropdown-toggle" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://avatars.githubusercontent.com/u/147168485?v=4" />
                  <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                    <%= link_to "Dashboard", new_user_session_path, class:"dropdown-item" %>
                    <%= link_to "Log out", destroy_user_session_path, data: { turbo_method: :delete}, class:"dropdown-item" %>
                  </div>
                </li>
              <% else %>
                <li class="nav-item">
                <%= link_to "Log in", new_user_session_path, class:"nav-link" %>
                </li>
              <% end %>
              <!--li class="nav-item"-->
              <!--/li-->
          </ul>
        </div>
      </div>
    </div>

    <%# <%= render 'flashes' %>

    <%= yield %>
  </body>

    <div class="footer">
      <div class="footer-logo">
        <%= image_tag "brainz-logo-final.png", class:"logo" %>
      </div>

      <div class="footer-links">
        <a href="#"><i class="fab fa-github" style="color: #EBC1F1"></i></a>
        <a href="#"><i class="fab fa-instagram" style="color: #EBC1F1"></i></a>
        <a href="#"><i class="fab fa-facebook" style="color: #EBC1F1"></i></a>
        <a href="#"><i class="fab fa-twitter" style="color: #EBC1F1"></i></a>
      </div>
    </div>
  </div>
</html>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/reviews/new.html.erb
<div class="add-review-form">
  <div class="row">
    <div class="col">
      <h1>What do you think about <%= @brain.name %>?</h1>

      <%= simple_form_for [@brain, @review] do |f| %>
        <%= f.input :comment, input_html: { class: 'input comment' } %>
        <%= f.input :rating %>
        <br>
        <%= f.submit 'Submit', class: "btn filter__btn" %>
      <% end %>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="container">
  <div class="row">
    <div class="col">
      <div class="username">
        <h2>
          Welcome <%= @user.first_name %> <%= @user.last_name %> !
        </h2>
        <%= link_to "Edit my profile", edit_user_registration_path(@user), class: "main-button" %>
      </div>

    <h2 class="dashboard-title">All my brains</h2>
      <div class="content">
  <div class="grid__cards-dashboard mb-5">
    <% @brains.each do |brain| %>
      <%= link_to brain_path(brain) do %>
        <div class="card-index">
          <div class="container-image mb-3">
            <% if brain.photo.attached? %>
              <%= cl_image_tag(brain.photo.key) %>
            <% else %>
              <%= image_tag("brainzImage.png", alt: "Brain Image") %>
            <% end %>
            <div class="qi">
              <div class="card-index__title">QI:</div>
              <div class="card-index__text-QI"><%= brain.qi %></div>
            </div>
          </div>
          <div class="card-infos">
            <div class="card-infos__attributes">
              <h2 class="card-index__name mb-3"><%= brain.name %></h2>

              <div class="d-flex align-items-start">
                <h3 class="card-index__title">Language(s):</h3>
                <div>
                  <% brain.languages.each do |language| %>
                    <p class="card-index__text"><%= language %></p>
                  <% end %>
                </div>
              </div>
              <div class="d-flex align-items-start">
                <h3 class="card-index__title">Specialties:</h3>
                <div>
                  <% brain.specialties.each do |specialty| %>
                    <p class="card-index__text"><%= specialty %></p>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
          <div>
            <h3 class="card-index__title">Price / Day:</h3>
            <div class="card-index__text-price"><%= brain.price_per_day %> €</div>
          </div>
        </div>
      <% end %>
    <% end %>
  </div>
  <div class="add-a-brain">
    <%= link_to "Add a brain", new_brain_path, class: "main-button" %>
  </div>
</div>

      <div class="card-bookings-dashboard">
        <h2 class="dashboard-title">All my bookings</h2>
        <div class="grid__cards-bookings mb-5">
          <% @bookings.each do |booking| %>
            <div class="card-booking">
              <div class="card-booking-infos">
                <h3><%= booking.brain.name %></h3>
                <div class="booking-date">
                  <p><strong>Start date :  </strong><%= booking.start_date %></p>
                  <p><strong>End date :  </strong><%= booking.end_date %></p>
                </div>
                <div class="cancel-booking">
                  <%= link_to "Cancel", brain_booking_path(booking.brain_id, booking) , class: "btn filter__btn", data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
                </div>
              </div>
          </div>
          <% end %>
        </div>
      </div>

    </div>
  </div>
</div>
<div class="card-bookings-dashboard">
  <h2 class="dashboard-title">All my booking requests</h2>
  <div class="grid__cards-bookings mb-5">
    <% @received_bookings.each do |booking| %>
      <div class="card-booking">
        <div class="card-booking-infos">
          <p><strong>Start date : </strong><%= booking.start_date %></p>
          <p><strong>End date : </strong><%= booking.end_date %></p>
          <p><strong>Price : </strong><%= booking.total_price %> €</p>
          <%= link_to 'Accept', accept_brain_booking_path(booking.brain, booking), data: { turbo_method: :patch }, class: 'btn filter__btn my-3' %>
          <%= link_to 'Reject', reject_brain_booking_path(booking.brain, booking), data: { turbo_method: :patch }, class: 'btn filter__btn my-3' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

<div class="delete-account">
  <%= link_to "Delete my account", cancel_user_registration_path, class: "main-button", data: { turbo_method: :delete, turbo_confirm: "Are you sure?"} %>
</div>

<%= render "shared/flashes" %>